### ISSUE TITLE
《背包问题9讲》2.0 Beta

### ISSUE THREAD

**Issue by lightyears1998** [GZHU-FightingTheLandlord/Templates#4]
Check: https://github.com/tianyicui/pack/blob/master/V2.pdf

: )

**Comment by semon0x29a** [comment]
Actually, it‘s already uploaded by Chocoboo 17 hours ago.
Thanks~

**Comment by lightyears1998** [comment]
The release date of your upload is 2011/09/28, while the lastest version is released on 2012/05/08.

**Comment by semon0x29a** [comment]
You're right. I will replace it soon.
Thank you~

**Comment by MoogleAndChocobo** [comment]
23333, it is my fault

**Comment by ConanYu** [comment]
Please speak CHINESE !!!

**Comment by ConanYu** [comment]
大佬喝茶。
