### ISSUE TITLE
Another Implement of KMP

### ISSUE THREAD

**Issue by lightyears1998** [GZHU-FightingTheLandlord/Templates#5]
https://github.com/GZHU-FightingTheLandlord/Templates/blob/f943e304cad2516508583d54c543989c8e184809/DynamicProgramming/KMP1.0--tested.cpp#L24-L63

Another implement:
```cpp
int pre[maxN]; 
char s[maxN], p[maxN];  // 文本串、模板串 

void prepare() {
	fill(pre, pre+maxN, -1);
	for (int i=1, j=-1; p[i]; ++i)  
	{
		while (j>=0 && p[i] != p[j+1]) j = pre[j];
		if (p[i] == p[j+1]) ++j;
		pre[i] = j;
	}
}

void kmp(vector<int> &match)
{
	match.clear(); prepare();
	for (int i=0, j=-1; s[i]; ++i) {
		while (j>=0 && s[i] != p[j+1]) j = pre[j];
		if (s[i] == p[j+1]) ++j;
		if (!p[j+1]) {  // 匹配成功 
			match.push_back(i-j);
		}
	}
}

```

**Comment by semon0x29a** [comment]
I don't know about kmp. I'll report it to SuDalao.
: )

**Comment by MoogleAndChocobo** [comment]
thx dalao for helping~ 
I'll add it to our repository~

**Comment by lightyears1998** [comment]
https://github.com/GZHU-FightingTheLandlord/Templates/blob/c6cf07b2340a83bdb1b7f8a15a941f60ed0d9599/DynamicProgramming/KMP2.0.cpp#L28-L29

p不是字符串的时候要小心修改这个条件，然后最好是用`j=pre[j]`带一下…… （来自下午的某次WA）
